import type { HubLayout } from '../types/hub';
import { CANVAS_HEIGHT, CANVAS_WIDTH } from '../types/hub';

export const DEFAULT_HUB_ID = 'demo-broadcast-hub';

export function createDefaultHub(): HubLayout {
  const now = new Date().toISOString();

  return {
    id: DEFAULT_HUB_ID,
    hubName: 'Championship Live Hub',
    game: 'League of Legends',
    canvas: {
      width: CANVAS_WIDTH,
      height: CANVAS_HEIGHT,
    },
    elements: [
      {
        id: 'widget-game-clock',
        name: 'Game Clock',
        type: 'data-widget',
        x: 870,
        y: 32,
        width: 180,
        height: 72,
        zIndex: 10,
        dataBinding: 'game.time',
        content: { label: 'TIME', showLabel: false },
        style: {
          color: '#f8fafc',
          backgroundColor: 'rgba(8, 13, 24, 0.88)',
          borderColor: 'rgba(255,255,255,0.24)',
          borderWidth: 1,
          borderRadius: 6,
          fontFamily: 'Inter, Arial, sans-serif',
          fontSize: 34,
          fontWeight: 800,
          textAlign: 'center',
          padding: 10,
        },
      },
      {
        id: 'widget-blue-gold',
        name: 'Blue Gold',
        type: 'data-widget',
        x: 510,
        y: 40,
        width: 220,
        height: 68,
        zIndex: 9,
        dataBinding: 'blueTeam.gold',
        content: { label: 'BLUE GOLD', showLabel: false },
        style: {
          color: '#dbeafe',
          backgroundColor: 'rgba(14, 46, 89, 0.9)',
          borderRadius: 6,
          fontSize: 30,
          fontWeight: 800,
          textAlign: 'center',
          padding: 10,
        },
      },
      {
        id: 'widget-red-gold',
        name: 'Red Gold',
        type: 'data-widget',
        x: 1190,
        y: 40,
        width: 220,
        height: 68,
        zIndex: 9,
        dataBinding: 'redTeam.gold',
        content: { label: 'RED GOLD', showLabel: false },
        style: {
          color: '#fee2e2',
          backgroundColor: 'rgba(98, 26, 42, 0.9)',
          borderRadius: 6,
          fontSize: 30,
          fontWeight: 800,
          textAlign: 'center',
          padding: 10,
        },
      },
      {
        id: 'widget-latest-event',
        name: 'Latest Event',
        type: 'data-widget',
        x: 610,
        y: 945,
        width: 700,
        height: 74,
        zIndex: 8,
        dataBinding: 'currentEvent',
        content: { label: 'LIVE EVENT', showLabel: false },
        style: {
          color: '#f8fafc',
          backgroundColor: 'rgba(15, 23, 42, 0.86)',
          borderColor: 'rgba(45, 212, 191, 0.55)',
          borderWidth: 1,
          borderRadius: 6,
          fontSize: 24,
          fontWeight: 700,
          textAlign: 'center',
          padding: 12,
        },
      },
    ],
    updatedAt: now,
  };
}
